environment:
  major_minor_version: "0.0"

version: $(major_minor_version).{build}-rc1

assembly_info:
  patch: true

platform: Any CPU
configuration: [Debug, Release]
after_build:
  - tools\package_on_debug.cmd %CONFIGURATION% %APPVEYOR_BUILD_FOLDER% %APPVEYOR_BUILD_VERSION%
  - tools\package_on_release.cmd %CONFIGURATION% %APPVEYOR_BUILD_FOLDER% %APPVEYOR_BUILD_VERSION%
  - tools\push_artifacts.cmd %APPVEYOR_BUILD_FOLDER% %APPVEYOR_BUILD_VERSION%
